language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: npm run test
    - stage: release
      name: "Release"
      script: npm run build
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
